export const PRODUK_TANI = [
  {
    id: "1",
    nama: "Padi Ciherang Unggul",
    petani: "Poktan Merdeka",
    lokasi: "Pringsewu, Lampung",
    stok: "5 Ton",
    kesehatan: "Sehat",
    siapPanen: "80%",
    harga: 12000,
    gambar: "/padi.jpg",
  },
  {
    id: "2",
    nama: "Cabai Merah Keriting",
    petani: "Gapoktan Siger Tani",
    lokasi: "Lampung Selatan",
    stok: "2.4 Ton",
    kesehatan: "Sangat Baik",
    siapPanen: "65%",
    harga: 28000,
    gambar: "/image/gambar1.jpg",
  },
  {
    id: "3",
    nama: "Jagung Hibrida",
    petani: "Kelompok Tani Jaya",
    lokasi: "Lampung Timur",
    stok: "4.1 Ton",
    kesehatan: "Baik",
    siapPanen: "72%",
    harga: 8500,
    gambar: "/image/gambar2.jpg",
  },
  {
    id: "4",
    nama: "Kubis Segar",
    petani: "Mitra Tani Sejuk",
    lokasi: "Liwa, Lampung Barat",
    stok: "1.8 Ton",
    kesehatan: "Baik",
    siapPanen: "91%",
    harga: 7000,
    gambar: "/image/gambar_kubis.jpg",
  },
];
